# Generated by Django 4.1.13 on 2024-01-25 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookingservice',
            unique_together={('booking', 'service', 'style')},
        ),
    ]
